### ISSUE TITLE
README.md might be wrong

### ISSUE THREAD

**Issue by koetsuserizawa** [nuitsjp/docker-md2review#1]
# Wrong
サポートしているタグ
md2reviewのバージョン毎にイメージを作成しています。 現在存在しているタグは latest, 1.12 です。

$ docker pull nuitsjp/docker-md2review:1.12

# Fix
サポートしているタグ
md2reviewのバージョン毎にイメージを作成しています。 現在存在しているタグは latest, 1.12 です。

$ docker pull nuitsjp/md2review:1.12

yorosiku onegaisimasu!

**Comment by nuitsjp** [comment]
ありがとうございます。
ちょっと今仕事で死にそうなのでなんとか2週間以内くらいには対応いたします。多分・・・死んでなければ・・・・

**Comment by koetsuserizawa** [comment]
がががががんばってください・・・・・・・・。いきて・・・・・・。

**Comment by nuitsjp** [comment]
Tag名も間違っていたのであわせて修正しました・・・
ありがとうございました！
